encoding: utf-8

# SEOç›¸å…³ä¿¡æ¯
title: ç¼¤çº·ç§‘æŠ€ç«™
description: Zebçš„è½¯ä»¶åšå®¢
keywords: TMaize,Blog,Java,Html,JavaScript
author: Zeb
footerText: 'Copyright Â© Zeb'

#ä¸ªæ€§ç­¾å(å»ºè®®ä¸è¶…è¿‡10ä¸ªä¸­æ–‡ï¼‰
Signature: ä¸–é—´ç™¾æ€ äººæ€§ä¸‘æ¶

# è¿™äº›ä¸è¦åŠ¨
permalink: /posts/:year/:month/:day/:title.html
kramdown:
  auto_ids: true
  input: GFM
  syntax_highlighter: rouge
exclude: ['CNAME', 'README.md', 'LICENSE', '_site', 'dist', 'Gemfile', 'Gemfile.lock', 'blog.sh']

# åŸŸåé…ç½®
# baseurlé…ç½®,å¦‚æœç½‘ç«™éƒ¨ç½²åœ¨æ ¹ç›®å½•ä¸‹çš„å…¶ä»–ç›®å½•ä¸­ï¼Œè¯·è®¾ç½®ä¸º /ç›®å½•å
domainUrl: 'https://bfkjz.github.io'
baseurl: ''

# ä½¿ç”¨jsdelivråŠ é€Ÿjså’Œcssæ–‡ä»¶'https://cdn.staticaly.com/gh/bfkjz/bfkjz.github.io/master'
jsdelivr: 'https://cdn.jsdelivr.net/gh/bfkjz/bfkjz.github.io'

#è®¾ç½®ä¸Šæµ·æ—¶åŒºï¼Œè§£å†³å½“å¤©çš„postä¸æ˜¾ç¤ºé—®é¢˜
timezone: Asia/Shanghai  

#å¤„ç†æœªæ¥æ—¶é—´çš„post
future: true

# åä¸ªæ§½åœ°å€ï¼Œä¼šåœ¨chaté¡µé¢ä¸­é‡å®šå‘åˆ°è¯¥åœ°å€
tucaoUrl: https://support.qq.com/products/325083

# ç”³è¯·å‹é“¾è¡¨å•æ˜¾ç¤ºåç§°ã€åœ°å€
linksName: é‡‘å±±æ–‡æ¡£( Wps )
linksUrl: https://f.wps.cn/w/UZUFVIu7

# èœå•
menu:
  - title: é¦–é¡µ
    url: /
  - title: å½’ç±»
    url: /pages/categories.html
  - title: å‹é“¾
    url: /pages/links.html
  - title: ç•™è¨€
    url: /pages/chat.html
  - title: å…³äº
    url: /pages/about.html
  - title: ğŸ”ï¸
    url: /pages/search.html

# ç‚¹å‡»é¡µé¢æ–‡å­—å†’å‡ºç‰¹æ•ˆ,ä¸éœ€è¦è¯·è®¾ç½®ä¸ºfalse
extClickEffect: true

# Google Adsense,ä¸éœ€è¦è¯·è®¾ç½®ä¸ºfalse
# _includes/ext-adsense.html é‡Œé¢ä¿®æ”¹ä¸ºè‡ªå·±çš„é…ç½®
extAdsense: false

# æ•°å­¦å…¬å¼æ”¯æŒï¼Œæ¯”è¾ƒå½±å“åŠ è½½é€Ÿåº¦,ä¸éœ€è¦è¯·è®¾ç½®ä¸ºfalse
extMath: false

# å‹æƒ…é“¾æ¥
links:
  - title: ç¼¤çº·ç§‘æŠ€ç«™
    url: https://bfkjz.github.io
    desc: ä¸–é—´ç™¾æ€ äººæ€§ä¸‘æ¶
    icon: https://bfkjz.github.io/static/img/logo.jpg
